# Generated by Django 4.1 on 2022-11-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewuser',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
