# Generated by Django 4.1 on 2022-10-31 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faq_review', '0002_frequentlyaskedquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewuser',
            name='date_add',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
