
# Generated by Django 4.1 on 2022-10-29 09:36

# Generated by Django 4.1 on 2022-10-29 07:17
# Generated by Django 3.2.15 on 2022-10-28 10:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/image_profile/'),
        ),
    ]
