# Generated by Django 4.1 on 2022-10-29 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendation', '0004_delete_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.URLField(max_length=255)),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendation.province')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.URLField(max_length=255)),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendation.province')),
            ],
        ),
    ]
