# Generated by Django 4.1 on 2022-10-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things_to_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='nama',
            field=models.CharField(max_length=255),
        ),
    ]
