# Generated by Django 4.1 on 2022-10-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things_to_do', '0002_alter_event_nama'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tanggal',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='deskripsi',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='gambar',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='deskripsi',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='gambar',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='nama',
            new_name='name',
        ),
    ]
