# Generated by Django 4.1 on 2022-10-29 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
        ('things_to_do', '0003_rename_tanggal_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendation.province'),
        ),
        migrations.AddField(
            model_name='food',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendation.province'),
        ),
    ]
