# Generated by Django 4.1 on 2022-10-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_auto_20221028_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
