# Generated by Django 3.2.15 on 2022-11-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_auto_20221101_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='image',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='image',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
